Model:
  mode: 'multi-label'  # multi-class  multi-label
  embed_dim: 8
  num_experts: 3
  num_tasks: 4
  units: 128
  tower_units: 32
  tower_hidden_units: [128, 64]   # [32, 16, 8]
  expert_hidden_units: [1024, 512, 256]    # [512, 256, 128]
  dropout: 0.5
  use_bn: False
  loss: ''  # focalloss

Train:
  lr: 0.004
  batchSize: 4096  
  milestones: [15, 30, 45]
  gamma: 0.5
  epochs: 150
  numWorkers: 16
  stage: [0]
  
Test:
  batchSize: 4096

Seed: 2021
  