Model:
  mode: 'multi-label'
  embed_dim: 4
  num_experts: 3
  units: 64
  tower_hidden_units: [32, 16, 8]
  expert_hidden_units: [512, 256, 128]
  dropout: 0.5
  use_bn: True
  loss: ''  # focalloss
  
Data:
  trainFilePath: '../data/train_dataset_0124.txt'  # _sample
  testFilePath: '../data/test_dataset_0124.txt'

Train:
  lr: 0.004
  batchSize: 4096
  milestones: [10, 20, 30]
  gamma: 0.5
  epochs: 100
  numWorkers: 16

Seed: 2021